appname: gindriver

db:
  name: FileFree
  user: postgres
  pass: postgres
  host: "110.43.42.250"
  port: 5432
  param: "charset=utf8&loc=Local"

listenaddr: "127.0.0.1:60082"
rpid: "www.bickik.com"
rporigin: "https://www.bickik.com/"
rpdisplayname: "FileFree"
